version: "3"
services:
  mongo:
    image: mongo:6.0.4
    ports:
      - "127.0.0.1:27017:27017"
    command: [ --replSet, rs0 ]
    volumes:
      - mongo_data:/data/db
      - ./conf/01.replica-set.init.js:/docker-entrypoint-initdb.d/01-replica-set.init.js
    networks:
      - mongo

volumes:
  mongo_data:
    external: true

networks:
  mongo:
    external: true
