services:
  portainer:
    image: portainer/portainer:1.25.0
    ports:
      - 127.0.0.1:9000:9000
    restart: always
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
